package solutions.fluidity.test.premiershipapi.model.boostrapstatic

class ElementModel {
    var chance_of_playing_next_round: Long? = null
    var chance_of_playing_this_round: Long? = null
    var code: Long? = null
//    var cost_change_event: Long? = null
//    var cost_change_event_fall: Long? = null
//    var cost_change_start: Long? = null
//    var cost_change_start_fall: Long? = null
    var dreamteam_count: Long? = null
    var element_type: Long? = null
//    var ep_next: String? = null
//    var ep_this: String? = null
    var event_points: Long? = null
    var first_name: String? = null
    var form: String? = null
    var id: Long? = null
    var in_dreamteam: String? = null
//    var news: String? = null
//    var news_added: String? = null
    var now_cost: Long? = null
    var photo: String? = null
    var points_per_game: String? = null
    var second_name: String? = null
    var selected_by_percent: String? = null
//    var special: String? = null
//    var squad_number: Long? = null
    var status: String? = null
    var team: Long? = null
    var team_code: Long? = null
    var total_points: Long? = null
    var transfers_in: Long? = null
    var transfers_in_event: Long? = null
    var transfers_out: Long? = null
    var transfers_out_event: Long? = null
    var value_form: String? = null
    var value_season: String? = null
    var web_name: String? = null
    var minutes: Long? = null
    var goals_scored: Long? = null
    var assists: Long? = null
    var clean_sheets: Long? = null
    var goals_conceded: Long? = null
    var own_goals: Long? = null
    var penalties_saved: Long? = null
    var penalties_missed: Long? = null
    var yellow_cards: Long? = null
    var red_cards: Long? = null
    var saves: Long? = null
    var bonus: Long? = null
    var bps: Long? = null
    var influence: String? = null
    var creativity: String? = null
    var threat: String? = null
    var ict_index: String? = null
    var influence_rank: Long? = null
    var influence_rank_type: Long? = null
    var creativity_rank: Long? = null
    var creativity_rank_type: Long? = null
    var threat_rank: Long? = null
    var threat_rank_type: Long? = null
    var ict_index_rank: Long? = null
    var ict_index_rank_type: Long? = null
//    var corners_and_indirect_freekicks_order: String? = null
//    var corners_and_indirect_freekicks_text: String? = null
//    var direct_freekicks_order: String? = null
//    var direct_freekicks_text: String? = null
//    var penalties_order: String? = null
//    var penalties_text: String? = null
}